apiVersion: v1
kind: PersistentVolume          
metadata:
  name: {{ template "mysqlchart.fullname" . }}-pv
  labels:
    type: local
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"      
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  hostPath:                       
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain   
---    
apiVersion: v1
kind: PersistentVolumeClaim        
metadata:                          
  name: {{ template "mysqlchart.fullname" . }}-pvc
  labels:
    app: crudapp
spec:                              
  storageClassName: "{{ .Values.persistence.storageClass }}"      
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}               
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
