replicaCount: 1
image:
  repository: mysql:5.6
  pullPolicy: IfNotPresent
env:
 MYSQL_ROOT_PASSWORD: root
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
persistence:
  storageClass: standard
  size: 10Gi
  accessMode: ReadWriteOnce
serviceAccount:
  create: true
  annotations: {}
  name:
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 3306
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
